### PR TITLE
[WIP?] Support to the latest Ubuntu versions

### PR DESCRIPTION
**Pull request by danimesq**
Wasn't able to check in my Ubuntu 22.10 install if it works

- [ ] For Ubuntu 22.04 onwards, use another method https://askubuntu.com/a/1396066/739431 (as commented [here](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background/issues/9#issuecomment-1116193440))
- [ ] After done, close issues #9 and #18 via commit

### CODE REVIEW

**Comment by danimesq** [comment]
@PRATAP-KUMAR are you active?

**Comment by danimesq** [comment]
Whoa

I'll have to make another pull request for that checklist this merged PR have/had

**Comment by PRATAP-KUMAR** [comment]
Hi @danimesq are you raising another PR?

**Comment by danimesq** [comment]
I want to, and will do it, but I didn't started it yet. Supporting a different desktop environment will be a challenge for me.

**Pull request merged**
